services:
  - type: web
    name: jquants-chart-player
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_APP_ID
        value: jquants-chart-player
      - key: OAUTH_SERVER_URL
        sync: false
      - key: VITE_OAUTH_PORTAL_URL
        sync: false
      - key: OWNER_OPEN_ID
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: VITE_APP_TITLE
        value: J-Quants Chart Player
      - key: VITE_APP_LOGO
        value: ""
      - key: BUILT_IN_FORGE_API_URL
        sync: false
      - key: BUILT_IN_FORGE_API_KEY
        sync: false

